apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: nfs-csi-kasm
provisioner: nfs.csi.k8s.io
parameters:
  server: ${nas_ip}
  share: ${root_path}/kasm
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - hard
  - nfsvers=4.1


